version: 2
jobs:
  build:
    docker:
      - image: berzns/ubuntunetcore:v1
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      #- run:
          #name: Build Solution
          #command: ./build.sh
  deploy:
    docker:
      - image: microsoft/azure-cli
    steps:
      - run:
        name: Authenticate
        command: az login --service-principal -t $TENANT -u $USER -p $SECRET

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
