version: 2
jobs:
  build:
    docker:
      - image: berzns:ubuntunetcore
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Build Solution
          command: ./build.sh